### ISSUE TITLE
No NewXXXProtobufClient method

### ISSUE THREAD

**Issue by nawuko** [donutloop/xservice#12]
**Description**

The generated protobuf files currently don't have "NewXXXProtobufClient" method, only a JSON client exists, also the generated code can only handle json content-types.

**Steps to reproduce the issue:**

1. Follow the example given in the readme
2. See compile error

**XService Version:**

- master
- 0.1.0

**Comment by donutloop** [comment]
That is a bug in the example. I do have plans to implement support for proto buffer content type handling.  I will release a new version in the upcoming days or weeks.  Thanks for your report!

**Comment by nawuko** [comment]
Okay, thank you 👍 

Also being very nit picky, but the comment on line https://github.com/donutloop/xservice/blob/03c7cde99a99460e1c4939d8ae580c69fba65f86/generator/proto/go/api.go#L235 should be `// Client` i guess
